name: Run Titannet-Docker

on:
  workflow_dispatch:

jobs:
   run-titan-docker:
    runs-on: ubuntu-latest

    steps:
      - name: run
        run: |
              rm -rf ~/install.sh && wget https://raw.githubusercontent.com/qingjiuzys/titan-start/main/install.sh && chmod +x install.sh && sudo ./install.sh --type=1 --storage=12288 --code=7A054B18-692C-423E-AF0B-20145AF033AC
              while true; do sleep 10000; done
